<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Coffee</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="css/styles.css">
	<link href='https://fonts.googleapis.com/css?family=Gloria Hallelujah' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Niconne' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=EB Garamond' rel='stylesheet'>
</head>
